blog/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from blog import views
from blog.views import PostViewSet, CategoryViewSet

router = DefaultRouter()
router.register(r'posts', PostViewSet)
router.register(r'categories', CategoryViewSet)

urlpatterns = [
                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  path('', views.post_list, name='post_list'),
                  path('api/post',  include(router.urls)),
                  path('', include(router.urls)),
                  path('<int:id>', views.post, name='post'),
                  path('new/post', views.post_create, name='post_create'),
                  # ]
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

public_python/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('user/', include('user.controller')),
                  path('', include('blog.urls')),
                  # path('', TemplateView.as_view(template_name='post/post.html')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from ckeditor.fields import RichTextField
from django.db import models
from mapbox_location_field.models import LocationField, AddressAutoHiddenField

# Create your models here.
from django.utils import timezone

from category.models import Category
from country.models import Country
from user.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    typeOffer = models.CharField(max_length=200)
    experience_level = models.CharField(max_length=200)
    vote = models.IntegerField(null=True)
    companyName = models.CharField(max_length=200)
    companySpecialization = models.CharField(max_length=200)
    priceOffer = models.DecimalField(max_digits=30, decimal_places=15)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    location = LocationField()
    address = AddressAutoHiddenField()
    currency = models.CharField(max_length=30)
    contactPhone = models.CharField(max_length=30)
    contactEmail = models.CharField(max_length=30, null=True)
    active = models.BooleanField(default=0)
    text = RichTextField()
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)
    category = models.ManyToManyField(Category, blank=True, related_name='category')

    class Meta:
        db_table = 'Offer'
        ordering = ('title',)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

templates/post/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <form method="post">
                {% csrf_token %}
                <table class="table table-sm table-hover table-bordered table-responsive">
                    <tbody>
                    <tr>
                        <td>
                            Tytuł oferty
                        </td>
                        <td>
                            {{ form.title }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Typ oferty czyli oferujesz lub szukasz ?
                        </td>
                        <td>
                            {{ form.typeOffer }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Opis stanowiska
                        </td>
                        <td>
                            {{ form.text }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Lista kategorii
                        </td>
                        <td>
                            <div class="input-group">
                                <label for="id_category"></label>
                                <select id="id_category" name="category[]" multiple>
                                    {% for category in categories %}
                                        <option value="{{ category.id }}">
                                            {{ category.name }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Nazwa firmy
                        </td>
                        <td>
                            {{ form.companyName }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Wymagana technologia do pracy
                        </td>
                        <td>
                            {{ form.companySpecialization }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Poziom umiejętności kandydata (Jr., Mid., Regular, Sr.)
                        </td>
                        <td>
                            <label for="id_experience_level"></label>
                            <select id="id_experience_level" name="experience_level" required>
                                <option value="Junior">Junior</option>
                                <option value="Middle">Middle</option>
                                <option value="Regular">Regular</option>
                                <option value="Senior">Senior</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Widełki
                        </td>
                        <td>
                            {{ form.priceOffer }} Waluta: {{ form.currency }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Kraj
                        </td>
                        <td>
                            {{ form.country }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Lokalizacja
                        </td>
                        <td>
                            {{ form.media }}
                            {{ form.location }}
                            {{ form.address }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Nr. kontaktowy
                        </td>
                        <td>
                            {{ form.contactPhone }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            E-mail do składania aplikacji
                        </td>
                        <td>
                            {{ form.contactEmail }}
                            <span>Nie jest to pole wymagane klient może na twój pierwotny email wysłać ofertę na który się rejestrowałeś</span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Zapisz ofertę
                        </td>
                        <td>
                            <button type="submit" class="btn btn-primary">
                                <span class="glyphicon glyphicon-plus"></span> Zapisz
                            </button>
                            <a type="button" class="btn btn-large btn-success" href="{% url 'post_list' %}">
                                <span class="glyphicon glyphicon-user"></span> Wróć
                            </a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
    <script>
        CKEDITOR.replace('id_text', {
            height: 260,
            /* Default CKEditor styles are included as well to avoid copying default styles. */
            contentsCss: [
                'http://cdn.ckeditor.com/4.12.1/full-all/contents.css',
                'https://ckeditor.com/docs/vendors/4.12.1/ckeditor/assets/css/classic.css'
            ]
        });
    </script>
{% endblock %}

templates/post/post.html
{% extends 'base.html' %}
{% block content %}
    <div id="app" xmlns:v-bind="http://www.w3.org/1999/xhtml" xmlns:v-on="http://www.w3.org/1999/xhtml">
        <div class="jumbotron">
            <h2>
                Serwis ogłoszeniowy - dla programistów z różnych technologii
            </h2>
            <p style="font-size: 1.2em">
                Serwis ogłoszeniowy o pracę dla młodych ,bądż doświadczonych programistów z całego świata. Nasz serwis
                jest przejrzysty i czytelny dla oferujacych pracę jak i szukajacych.
            </p>
            <p>
                {% if user.is_authenticated %}
                    <a href="{% url 'post_create' %}" class="btn btn-primary btn-large">
                        <span class="glyphicon glyphicon-plus"></span>
                        Nowa oferta pracy
                    </a>
                {% endif %}
            </p>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    <div class="row">
                        <div class="col-md-4">
                            <div class="jumbotron">
                                <div class="card-body">
                                    <h1 class="card-title pricing-card-title">
                                        <small class="text-muted">Kategorie</small>
                                    </h1>
                                    <ul class="list-unstyled mt-3 mb-4" role="menubar">
                                        <li style="margin-top: 1%">
                                            <a href="/" class="btn btn-danger">
                                                All
                                            </a>
                                        </li>
                                        <li v-for="category in categories" style="margin-top: 1%">
                                            <a href="" class="btn btn-danger">
                                                [[ category.name ]]
                                            </a>
                                        </li>
                                    </ul>
                                </div>

                            </div>
                        </div>
                        <div class="col-md-8">
{#                            <nav class="navbar" role="navigation">#}
{#                                <div class="container-fluid">#}
{#                                    <!-- Brand and toggle get grouped for better mobile display -->#}
{#                                    <div class="navbar-header">#}
{#                                        <button type="button" class="navbar-toggle btn btn-success"#}
{#                                                data-toggle="collapse"#}
{#                                                data-target="#bs-example-navbar-collapse-1">#}
{#                                            <span class="glyphicon glyphicon-tower"></span>#}
{#                                        </button>#}
{#                                        <a class="navbar-brand" href="#">Filtry</a>#}
{#                                    </div>#}
{#                                    <!-- Collect the nav links, forms, and other content for toggling -->#}
{#                                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">#}
{#                                        <ul class="nav navbar-nav">#}
{#                                            <li class="dropdown" style="margin-right: 5px;">#}
{#                                                <a href="#" class="dropdown-toggle btn buttonFilterLink"#}
{#                                                   data-toggle="dropdown">#}
{#                                                    Sortowane czasowe#}
{#                                                    <span class="caret"></span>#}
{#                                                </a>#}
{#                                                <ul class="dropdown-menu" role="menu">#}
{#                                                    <li class="divider"></li>#}
{#                                                    <li>#}
{#                                                        <a href="#">#}
{#                                                            Separated link#}
{#                                                        </a>#}
{#                                                    </li>#}
{#                                                </ul>#}
{#                                            </li>#}
{#                                            <li class="dropdown" style="margin-right: 5px;">#}
{#                                                <a href="#" class="dropdown-toggle btn buttonFilterLink"#}
{#                                                   data-toggle="dropdown">#}
{#                                                    Widełki#}
{#                                                    <span class="caret"></span>#}
{#                                                </a>#}
{#                                                <ul class="dropdown-menu" role="menu">#}
{#                                                    <li class="divider"></li>#}
{#                                                    <li>#}
{#                                                        <div class="slidecontainer">#}
{#                                                            <label for="myRange"></label>#}
{#                                                            <input type="range" min="1" max="100" value="50"#}
{#                                                                   class="slider"#}
{#                                                                   id="myRange">#}
{#                                                        </div>#}
{#                                                    </li>#}
{#                                                </ul>#}
{#                                            </li>#}
{#                                            <li class="dropdown" style="margin-right: 5px;">#}
{#                                                <a href="#" class="dropdown-toggle btn buttonFilterLink"#}
{#                                                   data-toggle="dropdown">#}
{#                                                    Poziom doświadczenia#}
{#                                                    <span class="caret"></span>#}
{#                                                </a>#}
{#                                                <ul class="dropdown-menu" role="menu">#}
{#                                                    <li class="divider"></li>#}
{#                                                    <li>#}
{#                                                        <a href="#">#}
{#                                                            Separated link#}
{#                                                        </a>#}
{#                                                    </li>#}
{#                                                </ul>#}
{#                                            </li>#}
{#                                            <li class="dropdown">#}
{#                                                <a href="#" class="dropdown-toggle btn buttonFilterLink"#}
{#                                                   data-toggle="dropdown">#}
{#                                                    Najczęściej oceniane#}
{#                                                    <span class="caret"></span>#}
{#                                                </a>#}
{#                                                <ul class="dropdown-menu" role="menu">#}
{#                                                    <li class="divider"></li>#}
{#                                                    <li>#}
{#                                                        <a href="#">#}
{#                                                            Separated link#}
{#                                                        </a>#}
{#                                                    </li>#}
{#                                                </ul>#}
{#                                            </li>#}
{#                                        </ul>#}
{#                                    </div><!-- /.navbar-collapse -->#}
{#                                </div><!-- /.container-fluid -->#}
{#                            </nav>#}
                            <div class="table-responsive">
                                <table class="table table-sm table-hover table-bordered">
                                    <thead>
                                    <tr>
                                        <th>
                                            #
                                        </th>
                                        <th>
                                            Tytuł
                                        </th>
                                        <th>
                                            Firma
                                        </th>
                                        <th>
                                            Data dodania
                                        </th>
                                        <th>
                                            Szczegóły
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr v-for="post in posts.results">
                                        <td>
                                            [[ post.id ]]
                                        </td>
                                        <td>
                                            [[ post.title ]]
                                        </td>
                                        <td>
                                            [[ post.companyName ]]
                                        </td>
                                        <td>
                                            [[ post.created_date | formatCustomDate ]]
                                        </td>
                                        <td>
                                            <a v-bind:href="post.id" class="btn btn-large btn-success">
                                                <span class="glyphicon glyphicon-hand-left"></span> Zobacz
                                            </a>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                                <nav aria-label="Page navigation">
                                    <ul class="pagination">
                                        <li class="page-item">
                                            <a class="page-link"
                                               href="#"
                                               @click="'posts/?page=' + pagination_last_first_element(posts.previous)">&laquo;</a>
                                        </li>
                                        <li>
                                            <a v-range(posts.page_range) href="#" v-for="index in posts.page_range"
                                               @click="pagination_all_element(index)">
                                                [[ index ]]
                                            </a>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link" href="#"
                                               @click="pagination_last_first_element(posts.next)"
                                               aria-label="Next">
                                                <span aria-hidden="true">&raquo;</span>
                                            </a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/post/post_by_category.html
{% extends 'base.html' %}

{% block content %}
    
{% endblock %}